### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by perb96** [nfes-org/nfes-org.github.io#3]
## Description
I would like to contact someone from the chapter but there is no generic email, of "contact us" form to fill out. Thanks!
[Description of the feature]

**Comment by alin256** [comment]
@perb96 Thank you for your suggestion! 

I have now added the 'send e-mail' button to the bottom bar.
Do you think that it is sufficiently visible, or should we better add another one into the about?

**Comment by perb96** [comment]
I found it!But I think having it somewhere else more visible would be convenient!
Thanks,Patricia
    On Monday, September 13, 2021, 01:56:19 PM MDT, Sergey Alyaev ***@***.***> wrote:  
 
 


@perb96 Thank you for your suggestion!

I have now added the 'send e-mail' button to the bottom bar.
Do you think that it is sufficiently visible, or should we better add another one into the about?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alin256** [comment]
@perb96, it is now clearly visible in the about.
 https://nfes.org/about.html
With that, I call a day :)

Please do not hesitate to suggest any other improvements.

**Comment by perb96** [comment]
Looks great! Thanks!
    On Monday, September 13, 2021, 02:19:32 PM MDT, Sergey Alyaev ***@***.***> wrote:  
 
 


@perb96, it is now clearly visible in the about.
https://nfes.org/about.html
With that, I call a day :)

Please do not hesitate to suggest any other improvements.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
